export const T = {
  GET_USERS: "GET_USERS",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_ERROR: "GET_USERS_ERROR",
  // Types for get photos
  GET_PHOTOS: "GET_PHOTOS",
  GET_PHOTOS_SUCCESS: "GET_PHOTOS_SUCCESS",
  GET_PHOTOS_ERROR: "GET_PHOTOS_ERROR"
};
